---
title: "occurrence manual"
date: "`r paste0('built on ', Sys.Date())`"
author: "`r paste0('built w/ rgbif v', packageVersion('rgbif'), ' / spocc v', packageVersion('spocc'), ' / rbison v', packageVersion('rbison'))`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ropensci/occurrence-manual
description: "occurrence manual"
---

```{r echo=FALSE, results="hide"}
occ_pkgs <- c("rgbif", "spocc", "rbison", "rvertnet", "ecoengine", "auk")
```

# occurrence manual

This book covers a suite of R packages used in working with biological 
occurrence data

## Info

* Code: <https://github.com/ropensci/occurrence-manual/>
* Issues/Bug reports: Go to issue trackers for each package

Packages

* `rgbif`: <https://cran.rstudio.com/web/packages/rgbif/>
* `spocc`: <https://cran.rstudio.com/web/packages/spocc/>
* `rbison`: <https://cran.rstudio.com/web/packages/rbison/>
* `rvertnet`: <https://cran.rstudio.com/web/packages/rvertnet/>
* `ecoengine`: <https://cran.rstudio.com/web/packages/ecoengine/>
* `auk`: <https://cran.rstudio.com/web/packages/auk/>


## Installation

Stable version from CRAN

```{r eval=FALSE}
install.packages(c("rgbif", "spocc", "rbison", "rvertnet", "ecoengine", "auk"))
```
